name: Windows MSVC

on: [push, pull_request]

env:
  QTVER: 6.10.2
  FFMPEG_VERSION: 8.0.1
  CMAKE_GENERATOR: Visual Studio 17 2022

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Bypass Private Module & Download Public Features
      run: |
        git config -f .gitmodules --remove-section submodule."libAvKys/ExtraPlugins" || true
        git submodule update --init --recursive
      shell: bash
        
    - name: Install dependencies
      run: ./ports/ci/windows-msvc/install_deps.bat
      
    - name: Daily Build
      env:
        DAILY_BUILD: 1
      run: ./ports/ci/windows-msvc/build.bat
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webcamoid-windows-build
        path: build/
